# The Docker image that will be used to build your app
  image: node:20
# Functions that should be executed before the build script is run
  before_script:
    - npm install
  pages:
    cache:
      paths:
        - node_modules/

    script:
      - npm run generate
      - rm -rf ./public
      - mv ./.output/public ./public
    artifacts:
      paths:
        - public
 rules:
   # This ensures that only pushes to the default branch will trigger
   # a pages deploy
   - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH